services:
  - type: static_site
    name: lyfline-frontend
    env: node
    # The build command is now prefixed with 'cd LyflineFrontend &&'
    buildCommand: cd LyflineFrontend && npm install && npm run build
    # The publish directory is now relative to the repository root
    publishDir: ./LyflineFrontend/dist
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
    headers:
      - path: "/*"
        name: Cache-Control
        value: "no-cache" 