services:
  - type: static_site
    name: lyfline-frontend
    env: node
    buildCommand: npm install && npm run build
    publishDir: ./dist
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
    headers:
      - path: "/*"
        name: Cache-Control
        value: "no-cache" 