services:
  - type: web
    name: lyfline-frontend
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: false
    headers:
      - path: /*
        headers:
          - key: X-Frame-Options
            value: DENY
          - key: X-Content-Type-Options
            value: nosniff
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 