services:
  - type: web
    name: lyfline-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    headers:
      - path: /*
        headers:
          - key: Cache-Control
            value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 